# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: centos:7

    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run: 
          name: Change mirror list 
          command: sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo && sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
        
      - run:
          name: Install openssh-client
          command:  yum -y install openssh-clients
