# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2024.07

    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Install openssh-client
          command: sudo apt-get update && sudo apt-get install -y openssh-clients

